# Generated by Django 5.0.7 on 2024-07-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fiction', max_length=50),
            preserve_default=False,
        ),
    ]
